config/routes.rb
Rails.application.routes.draw do
  root to: 'categories#index', as: 'categories'
  get '/categories/:id', to: 'categories#show', as: 'category'
  
end

app/models/category.rb
class Category < ActiveRecord::Base

    has_many :subcategories, class_name: "Category", foreign_key: "parent_id", dependent: :destroy
    has_many :products, dependent: :destroy
    belongs_to :parent_category, class_name: "Category", foreign_key: "parent_id", optional: true
    validates_presence_of :name

    class << self

        def main_categories
            @@main_categories
        end

        def initialize_main_categories
            @@main_categories ||= Category.where(parent_id: nil).all
        end
    end

    def ancestor_ids ancestors = []
        if self.parent_id.present?
            self.parent_category.ancestor_ids ancestors        
        end
        ancestors << self.id
    end
end

app/models/product.rb
class Product < ActiveRecord::Base
    belongs_to :category, class_name: "Category"
    validates_presence_of :name
    validates_presence_of :category
    paginates_per 16

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :initialize_main_categories
  before_action :reorder_products, only: [:index, :show]

  def index
    @category = nil
    @categories = @main_categories
    @relevant_products = @ordered_products.page(params[:page])
  end

  def show
    @category = Category.find params[:id]
    @categories = @category.subcategories
    category_ids = @category.subcategory_ids << @category.id
    @relevant_products = @ordered_products.where(:category_id => category_ids).page(params[:page])
    
    render :action => :index
  end
  
  private 

  def initialize_main_categories
    Category.initialize_main_categories
    @main_categories = Category.main_categories
  end

  def reorder_products
    order_by = params[:order] ? params[:order].to_sym : :asc
    @ordered_products = Product.order(name: order_by)
  end

end

app/views/categories/_categories.html.erb
<div class="categories-data">
    <div class="title">
        <% if category.present? %>
            <% path_name = category.parent_id.present? ? category.parent_category.name : 'Main Categories'%>
            <% path =  category.parent_id.present? ? category_path(category.parent_id) : categories_path%>
            <%= link_to path_name, path, class: 'back-link' %>
            <h1 class="category-name"><%= category.name %></h1>
        <%else%>
            <h1>Our Categories</h1>
        <% end %>
    </div>
    
    <%if categories.present?%>
    <div class="ui grid padded">
        <% categories.each do |category| %>
            <div class="four wide column">
                <div class="ui card">
                    <div class="content">
                        <%= link_to category.name, category_path(category) %>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
    <% end %>
</div>

app/views/categories/_main_categories.html.erb
<% ancestors = selected_category.nil? ? [] : selected_category.ancestor_ids %>

<div id="main-categories-menu" class="ui secondary pointing menu">
    <% main_categories.each do |category| %>
        <% selected = ancestors.include?(category.id) %>
        <span class="item <%= "active" unless !selected %>">
            <%= link_to category.name, category_path(category) %>
        </span>
    <%end%>
</div>

app/views/categories/index.html.erb
<%= render partial: "main_categories", locals: { main_categories: @main_categories, selected_category: @category }, cached: true %>

<div id="catalog">
    <%= render partial: "categories", locals: {categories: @categories, category: @category}%>
    <%= render partial: "products/products", locals: {products: @relevant_products, category: @category} %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Catalog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_products.html.erb
<div class="products-data">
    <div class="products">
        <% unless products.empty? %>
            <div class="sort-by">Sort products by name: 
                <%= link_to "A-Z", url_for(order: 'ASC') %> /
                <%= link_to "Z-A", url_for(order: 'DESC') %>
            </div>
        <% end %>
        <div class="ui grid padded">
            <% products.each do |product| %>
                <div class="four wide column">
                    <div class="ui card">
                        <div class="content">
                            <%= product.name %>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
    <% unless products.empty? %>
        <%= paginate products %>
    <% end %>
</div>